spring:
  application:
    name: ms-products
  datasource:
    url: ${URL_DATABASE:jdbc:mysql://localhost:3306/database}
    username: root
    password: 60100440
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true
server:
  port: 8092

key: ABCDabcd1234

